name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: packages/

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: hh-plugin-migration
        working-directory: hh-plugin-migration/
        run: |
          yarn install
          yarn test

      # - name: hh-plugin-contracts
      #   working-directory: hh-plugin-contracts/
      #   run: |
      #     yarn install
      #     yarn test
